src/main/java/com/vaoru/climaplanetario/model/Planet.java
package com.vaoru.climaplanetario.model;


public class Planet extends SolarSystem{
	private String name;
	private int degreeRotacionXday;
	private int distanceXSun;
	private boolean  isRotationClockwiseClockDirection;
	
	
	public int getDegreeRotacionXday() {
		return degreeRotacionXday;
	}
	public void setDegreeRotacionXday(int degreeRotacionXday) {
		this.degreeRotacionXday = degreeRotacionXday;
	}
	public int getDistanceXSun() {
		return distanceXSun;
	}
	public void setDistanceXSun(int distanceXSun) {
		this.distanceXSun = distanceXSun;
	}
	public boolean isRotationClockwiseClockDirection() {
		return isRotationClockwiseClockDirection;
	}
	public void setRotationClockwiseClockDirection(boolean isRotationClockwiseClockDirection) {
		this.isRotationClockwiseClockDirection = isRotationClockwiseClockDirection;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public float getCompleteOrbitalLapInDays(){
		int unitTime = 1;
		int completeDegreeRotation = 360;
		float lapInDays = (completeDegreeRotation * unitTime) /  getDegreeRotacionXday() ;
		return lapInDays;
	}
	
}

src/main/java/com/vaoru/climaplanetario/model/ResultPlanetsPosition.java
package com.vaoru.climaplanetario.model;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.vaoru.climaplanetario.enums.ConfigApp;

@Entity
@Table(name = "Result_Planets_Position")
public class ResultPlanetsPosition {
	
	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
    @Column(name = "id")
    private String id;
	
	/**
	 * Planets to work.
	 */
	@Transient
	private List<Planet> planets;
	/**
	 * Day of the period of years.
	 */
	@Column(name = "timeInDay")
	private int timeInDay;
	/**
	 * If all the planets are alignment on a single line.
	 */
	@Column(name = "planetsAlignment")
	private boolean planetsAlignment;
	
	/**
	 * If all the planets and the sun are alignment on a single line.
	 */
	@Column(name = "planetsAndSunAlignment")
	private boolean planetsAndSunAlignment;
	
	/**
	 * If the sun is inside the triangle formed by the planets.
	 */
	@Column(name = "sunInsideTrianglePlanets")
	private boolean sunInsideTrianglePlanets;
	
	/**
	 * If the sun is center inside the triangle formed by the planets.
	 */
	@Column(name = "sunInsideMaxRainTrianglePlanets")
	private boolean sunInsideMaxRainTrianglePlanets;
	
	/**
	 * If the sun is outside the triangle formed by the planets.
	 */
	@Column(name = "sunOutsideTrianglePlanets")
	private boolean sunOutsideTrianglePlanets;
	/**
	 * Creation date.
	 */
	@Column(name = "creation")
	Date creation;
	
	@Transient
	private String resultWeatherReport;
	
	public List<Planet> getPlanets() {
		return planets;
	}
	public void setPlanets(List<Planet> planets) {
		this.planets = planets;
	}
	public int getTimeInDay() {
		return timeInDay;
	}
	public void setTimeInDay(int timeInDay) {
		this.timeInDay = timeInDay;
	}
	
	public void setPlanetsAlignment(boolean planetsAlignment) {
		this.planetsAlignment = planetsAlignment;
	}
	public boolean isPlanetsAlignment() {
		return planetsAlignment;
	}
	
	public boolean isPlanetsAndSunAlignment() {
		return planetsAndSunAlignment;
	}
	public void setPlanetsAndSunAlignment(boolean planetsAndSunAlignment) {
		this.planetsAndSunAlignment = planetsAndSunAlignment;
	}
	public boolean isSunInsideTrianglePlanets() {
		return sunInsideTrianglePlanets;
	}
	public void setSunInsideTrianglePlanets(boolean sunInsideTrianglePlanets) {
		this.sunInsideTrianglePlanets = sunInsideTrianglePlanets;
	}
	public boolean isSunInsideMaxRainTrianglePlanets() {
		return sunInsideMaxRainTrianglePlanets;
	}
	public void setSunInsideMaxRainTrianglePlanets(boolean sunInsideCenterTrianglePlanets) {
		this.sunInsideMaxRainTrianglePlanets = sunInsideCenterTrianglePlanets;
	}
	public boolean isSunOutsideTrianglePlanets() {
		return sunOutsideTrianglePlanets;
	}
	public void setSunOutsideTrianglePlanets(boolean sunOutsideTrianglePlanets) {
		this.sunOutsideTrianglePlanets = sunOutsideTrianglePlanets;
	}
	
	public String getResultWeatherReportText() {
		
		if ( !this.isPlanetsAndSunAlignment() && this.isPlanetsAlignment()){
			resultWeatherReport = ConfigApp.PERFECT_CONDITIONS_WEATHER.getValue();
		}else if(this.isPlanetsAndSunAlignment() && this.isPlanetsAndSunAlignment()){
			resultWeatherReport =ConfigApp.DROUGHT.getValue();
		}else if(this.isSunInsideTrianglePlanets()){
			resultWeatherReport =ConfigApp.RAIN.getValue();
		}else if(this.isSunInsideMaxRainTrianglePlanets()){
			resultWeatherReport =ConfigApp.MAX_RAIN.getValue();
		}else{
			resultWeatherReport =ConfigApp.SUN.getValue();
		}
		return resultWeatherReport;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public Date getCreation() {
		return creation;
	}
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	
	
}

src/main/java/com/vaoru/climaplanetario/HomeController.java
package com.vaoru.climaplanetario;

import java.util.Calendar;
import java.util.Locale;

import javax.annotation.PostConstruct;

import org.joda.time.LocalDate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.vaoru.climaplanetario.enums.ConfigApp;
import com.vaoru.climaplanetario.service.WeatherService;

/**
 * Handles requests for the application home page.
 */
@Controller
public class HomeController {
	
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	
	
	
	@Autowired
	private WeatherService weatherService;
	
	@PostConstruct
	private void init(){
		
	}
	
	/**
	 * Weather Report view.
	 */
	@RequestMapping(value = "/weatherreport", method = RequestMethod.GET)
	public String weatherreport(Locale locale, Model model) {
		Calendar calendar = Calendar.getInstance();
		calendar.set(Calendar.YEAR, calendar.get(Calendar.YEAR)+10);
		int daysToTenYears = weatherService.daysToTenYears(new LocalDate());
		model.addAttribute("appName", ConfigApp.APP_NAME.getValue());
		model.addAttribute("PERFECT_CONDITIONS_WEATHER", ConfigApp.PERFECT_CONDITIONS_WEATHER.getValue());
		model.addAttribute("DROUGHT", ConfigApp.DROUGHT.getValue());
		model.addAttribute("YES", ConfigApp.YES.getValue());
		model.addAttribute("NO", ConfigApp.NO.getValue());
		model.addAttribute("planets", weatherService.getPlanets());
		model.addAttribute("daysToTenYears", daysToTenYears);
		model.addAttribute("pronosticPlanetPositions", weatherService.pronosticPlanetPositions(daysToTenYears));
		model.addAttribute("counterDrought", weatherService.getLastCounterResultsReport().getCounterDrought());
		model.addAttribute("counterPerfectConditionsWeather", weatherService.getLastCounterResultsReport().getCounterPerfectConditionsWeather());
		model.addAttribute("counterRain", weatherService.getLastCounterResultsReport().getCounterRain());
		model.addAttribute("counterMaxRain", weatherService.getLastCounterResultsReport().getCounterMaxRain());
		return "weatherreport";
	}
	
	/**
	 * Weather Report view.
	 */
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		return "home";
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}

src/main/webapp/WEB-INF/views/home.jsp
<%@ page session="false" language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE HTML>
<!--
	Solid State by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>${appName}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="<c:url value="/resources/assets/css/main.css" />" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body>

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="index.html">${appName}</a></h1>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<div class="inner">
							<h2>Menu</h2>
							<ul class="links">
								<li><a href="<c:url value="/" />">Inicio</a></li>
								<li><a href="<c:url value="/weatherreport" />">Pronostico del clima</a></li>
								<li><a target="_blank" href="<c:url value="/v1/clima?dia=566" />">Servicio para civilizaciones REST API</a></li>
								<li><a target="_blank" href="https://bitbucket.org/iterreno/planetaryweather/overview">Ver repositorio en bitbucket</a></li>
							</ul>
							<a href="#" class="close">Cerrar</a>
						</div>
					</nav>

				<!-- Banner -->
					<section id="banner">
						<div class="inner">
							<div class="logo"><span class="icon fa-diamond"></span></div>
							<h2>DOMINAMOS LA PREDICCIÓN DEL CLIMA DEL SISTEMA SOLAR VULCANOS, FERENGIS Y BETAZOIDES .</h2>
							<p>PODEMOS PREDECIR EL CLIMA EN LOS PRÓXIMOS 10 AÑOS DEL SISTEMA SOLAR VULCANOS, FERENGIS Y BETAZOIDES. <a target="_blank" href="https://www.linkedin.com/in/ismael-terreno/"> Autor - Ismael Terreno</a></p>
						</div>
					</section>

				<!-- Wrapper -->
					<section id="wrapper">

						<!-- One -->
							<section id="one" class="wrapper spotlight style1">
								<div class="inner">
									<a href="#" class="image"><img src="<c:url value="/resources/images/ferengi-culture.jpg" />" alt="" /></a>
									<div class="content">
										<h2 class="major">Ferengi</h2>
										<p>
											Su cultura y psicología se caracteriza por una obsesión capitalista hacia el comercio y los beneficios. También son conocidos por su misoginia, de forma que sus mujeres tienen prohibido realizar cualquier tipo de transacción económica e ir vestidas en público. Proceden de Ferenginar, un planeta caracterizado por lluvias constantes, que está regido por el gran Negus, el ferengi más ambicioso, que tiene la enorme responsabilidad de que su ambición personal refleje la ambición pública. Como la mayor parte de su cultura, su religión está basada en el capitalismo.
										</p>
										<a target="_blank" href="https://es.wikipedia.org/wiki/Ferengi" class="special">Aprender mas</a>
									</div>
								</div>
							</section>

						<!-- Two -->
							<section id="two" class="wrapper alt spotlight style2">
								<div class="inner">
									<a href="#" class="image"><img src="<c:url value="/resources/images/vulcano-culture.jpeg" />" alt="" /></a>
									<div class="content">
										<h2 class="major">Vulcano</h2>
										<p>
										Alcanzada la adolescencia, los vulcanos se someten a ciertos ritos de paso, entre los que destacan el kolinahr, cuyo propósito es suprimir totalmente las emociones, y el tal’oth, referido a las habilidades de supervivencia del joven iniciado, el cual debe permanecer totalmente aislado durante cuatro meses en el desierto, armado sólo con una espada ceremonial para defenderse o conseguir alimentos.
										</p>
										<a target="_blank" href="https://es.wikipedia.org/wiki/Vulcano_(Star_Trek)" class="special">Aprender mas</a>
									</div>
								</div>
							</section>

						<!-- Three -->
							<section id="three" class="wrapper spotlight style3">
								<div class="inner">
									<a href="#" class="image"><img src="<c:url value="/resources/images/betazoides-culture.jpeg" />" alt="" /></a>
									<div class="content">
										<h2 class="major">Betazoide</h2>
										<p>
											La sociedad de Betazed tiende a tradiciones más formales y detalladas, con ceremonias que la mayoría de las culturas han eliminado en su fase evolutiva actual, como la ceremonia de boda tradicional en la que no se permite ninguna ropa.
										</p>
										<a target="_blank" href="https://es.wikipedia.org/wiki/Betazoide" class="special">Learn more</a>
									</div>
								</div>
							</section>

						

					</section>

				<!-- Footer -->
					<section id="footer">
						<div class="inner">

							<ul class="copyright">
								<li>&copy; Vaoru.</li><li>Design: <a href="http://www.vaoru.com">Vaoru Consulting</a></li>
							</ul>
						</div>
					</section>

			</div>

		<!-- Scripts -->
			<script src="<c:url value="/resources/assets/js/skel.min.js" />"></script>
			<script src="<c:url value="/resources/assets/js/jquery.min.js" />"></script>
			<script src="<c:url value="/resources/assets/js/jquery.scrollex.min.js" />"></script>
			<script src="<c:url value="/resources/assets/js/util.js" />"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="<c:url value="/resources/assets/js/main.js" />"></script>
	</body>
</html>

src/main/webapp/WEB-INF/views/weatherreport.jsp
<%@ page session="false" language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE HTML>
<!--
	Solid State by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>${appName}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="<c:url value="/resources/assets/css/main.css" />" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body>

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="<c:url value="/" />">${appName}</a></h1>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<div class="inner">
							<h2>Menu</h2>
							<ul class="links">
								<li><a href="<c:url value="/" />">Inicio</a></li>
								<li><a href="<c:url value="/weatherreport" />">Pronostico del clima</a></li>
								<li><a target="_blank" href="<c:url value="/v1/clima?dia=566" />">Servicio para civilizaciones REST API</a></li>
								<li><a target="_blank" href="https://bitbucket.org/iterreno/planetaryweather/overview">Ver repositorio en bitbucket</a></li>
							</ul>
							<a href="#" class="close">Cerrar</a>
						</div>
					</nav>

				<!-- Wrapper -->
					<section id="wrapper">
						<header>
							<div class="inner">
								<h2>Pronostico del clima a 10 años</h2>
								<p>Predicción del clima en base a la posición de los tres planetas.</p>
							</div>
						</header>

						<!-- Content -->
							<div class="wrapper">
								<div class="inner">

									<section>
										<h3 class="major">Condiciones climaticas</h3>
										<div class="row">
											<div class="12u 12u$(medium)">
												<h4>Escenarios</h4>
												<ul class="alt">
													<li>Cuando los tres planetas están alineados entre sí y a su vez alineados con respecto al sol, el sistema solar experimenta un período de sequía..</li>
													<li>Cuando los tres planetas no están alineados, forman entre sí un triángulo. Es sabido que en el momento en el que el sol se encuentra dentro del triángulo, el sistema solar experimenta un período de lluvia, teniendo éste, un pico de intensidad cuando el perímetro del triángulo está en su máximo.</li>
													<li>Las condiciones óptimas de presión y temperatura se dan cuando los tres planetas están alineados entre sí pero no están alineados con el sol..</li>
												</ul>
											</div>
											
										</div>
									</section>
									<section>
										<h3 class="major">Información de planetas</h3>
										<h4>Detalle</h4>
										<div class="table-wrapper">
											<table>
												<thead>
													<tr>
														<th>Nombre del Planeta</th>
														<th>Distacia al sol/Km</th>
														<th>Grados de rotacion por dia</th>
														<th title="Se saco con una regla de tres simple">Dias para vuelta completa orbital</th>
														<th>Direccion agujas del relog</th>
													</tr>
												</thead>
												<tbody>
													<c:forEach var="planet" items="${planets}">
														<tr>
															<td>${planet.name}</td>
															<td>${planet.distanceXSun}</td>
															<td>${planet.degreeRotacionXday}</td>
															<td>${planet.completeOrbitalLapInDays}</td>
															<td>
																<c:choose>
																    <c:when test="${planet.rotationClockwiseClockDirection}">
																       Si
																    </c:when>    
																    <c:otherwise>
																        No
																    </c:otherwise>
																</c:choose>
															</td>
														</tr>
													</c:forEach>
												</tbody>
												
											</table>
										</div>
										<h3 class="major">Calculos generales de planetas</h3>
										<h4>Detalle</h4>
										<div class="table-wrapper">
											<table>
												<thead>
													<tr>
														<th>Cantidad de Días a 10 años</th>
														<th>¿Cuántos períodos de sequía habrá?</th>
														<th>¿Cuántos períodos de lluvia habrá ?</th>
														<th>¿Qué día será el pico máximo de lluvia ?</th>
														<th>¿Cuántos períodos de condiciones óptimas de presión y temperatura habrá?</th>
													</tr>
												</thead>
												<tbody>
													<tr>
														<td>${daysToTenYears}</td>
														<td>${counterDrought}</td>
														<td>${counterRain}</td>
														<td>${counterMaxRain}</td>
														<td>${counterPerfectConditionsWeather}</td>
													</tr>
												</tbody>
												
											</table>
										</div>
										
										<div class="table-wrapper">
											<table class="alt">
												<thead>
													<tr>
														<th>Dìa</th>
														<th>Planetas alineados</th>
														<th>Planetas y Sol alineados</th>
														<th>Pronostico</th>
													</tr>
												</thead>
												<tbody>
													<c:forEach var="resultPlanetsPosition" items="${pronosticPlanetPositions}">
														<tr>
															<td>${resultPlanetsPosition.timeInDay}</td>
															<td>
																<c:choose>
																    <c:when test="${resultPlanetsPosition.planetsAlignment}">
																       Si
																    </c:when>    
																    <c:otherwise>
																        No
																    </c:otherwise>
																</c:choose>
															</td>
															<td>
																<c:choose>
																    <c:when test="${resultPlanetsPosition.planetsAndSunAlignment}">
																        Si
																    </c:when>    
																    <c:otherwise>
																         No
																    </c:otherwise>
																</c:choose>
															</td>
															<td>
																${resultPlanetsPosition.resultWeatherReportText}
															</td>
														</tr>
													</c:forEach>
												</tbody>
											</table>
										</div>
										
										</section>

								</div>
							</div>

					</section>

			</div>

		<!-- Scripts -->
			<script src="<c:url value="/resources/assets/js/skel.min.js" />"></script>
			<script src="<c:url value="/resources/assets/js/jquery.min.js" />"></script>
			<script src="<c:url value="/resources/assets/js/jquery.scrollex.min.js" />"></script>
			<script src="<c:url value="/resources/assets/js/util.js" />"></script>
			<!--[if lte IE 8]><script src="<c:url value="/resources/assets/js/ie/respond.min.js" />"></script><![endif]-->
			<script src="<c:url value="/resources/assets/js/main.js" />"></script>

	</body>
</html>